sentences = [
    "Football is the most popular sport in the world.",
    "The football match was intense, with both teams showing great skills.",
    "Millions of people around the world watch football every weekend.",
    "Football teams spend millions of dollars on player transfers.",
    "The World Cup is one of the biggest events in football.",
    "Lionel Messi is often regarded as one of the greatest football players of all time.",
    "Cristiano Ronaldo has won multiple Ballon d'Or awards.",
    "The Premier League is one of the most competitive football leagues.",
    "The Champions League final is watched by millions globally.",
    "Many football players come from humble backgrounds before achieving stardom.",
    "Football clubs have extensive youth academies to nurture young talent.",
    "The FIFA World Cup is held every four years.",
    "The fastest recorded goal in football was scored in just 2.8 seconds.",
    "Footballers train for hours every day to improve their skills and fitness.",
    "Stadiums can hold up to 100,000 spectators for major football events.",
    "The Ballon d'Or is awarded annually to the best football player in the world.",
    "Football teams from different countries compete in international tournaments.",
    "Referees play a crucial role in ensuring fairness during football matches.",
    "Goalkeepers are often the unsung heroes of football teams.",
    "Football fans create an electric atmosphere in the stadium during matches.",
    "Many football clubs have passionate fanbases that support their team.",
    "The offside rule is one of the most debated topics in football.",
    "Football matches are usually 90 minutes long, divided into two halves.",
    "Substitutes are an important part of modern football strategy.",
    "Football boots are designed to provide better grip on the pitch.",
    "Football has a rich history and has evolved over centuries.",
    "Women's football has grown significantly in popularity in recent years.",
    "Footballers often sign endorsement deals with major brands.",
    "Football clubs can generate millions in revenue through merchandising.",
    "The goalpost is 8 feet high and 8 yards wide in professional football.",
    "The offside rule helps prevent players from gaining an unfair advantage.",
    "Football teams often go on pre-season tours to different countries.",
    "Football's governing body, FIFA, is responsible for organizing global tournaments.",
    "Many footballers engage in charity work to give back to their communities.",
    "Football matches are watched in bars and homes all over the world.",
    "Some football players are known for their incredible speed on the pitch.",
    "Football teams have medical staff to take care of injured players.",
    "Football players wear protective gear such as shin guards and socks.",
    "Football clubs spend large amounts on scouting new players.",
    "The World Cup has been won by multiple countries throughout history.",
    "Football teams often change their team line-ups depending on the opponent.",
    "Football clubs sometimes face financial difficulties due to poor management.",
    "Football is played with a spherical ball on grass or artificial turf.",
    "The FIFA rankings determine the strength of national football teams.",
    "The Golden Boot is awarded to the top goal scorer in a competition.",
    "Footballers are often role models for young people around the world.",
    "Tactics and formations are key aspects of football strategy.",
    "Football fans travel long distances to support their teams.",
    "Football is known for its passionate rivalries, such as El Clásico.",
    "Football has inspired movies, books, and documentaries.",
    "The Premier League attracts top-tier football talent from all over the world.",
    "Football teams spend a significant amount on player wages.",
    "Technology like VAR (Video Assistant Referee) is now used in football.",
    "Football matches are played in various weather conditions, from sun to rain."
]

prompts = [
    "What is the most popular sport in the world?",
    "How intense was the football match?",
    "How many people watch football?",
    "How much money do football teams spend?",
    "What is one of the biggest events in football?",
    "Why is Lionel Messi regarded as one of the greatest players?",
    "How many Ballon d'Or awards has Cristiano Ronaldo won?",
    "Which football league is considered the most competitive?",
    "When is the Champions League final watched by millions?",
    "What is the background of many professional football players?",
    "What do football clubs do to nurture young talent?",
    "How often is the FIFA World Cup held?",
    "How quickly was the fastest goal in football scored?",
    "How do footballers improve their skills and fitness?",
    "How many spectators can major football stadiums hold?",
    "What is awarded annually to the best football player?",
    "What tournaments do football teams from different countries compete in?",
    "Why are referees important in football?",
    "What role do goalkeepers play in a football team?",
    "How do football fans contribute to the atmosphere in the stadium?",
    "What is significant about football clubs' fanbases?",
    "What is a commonly debated topic in football?",
    "How long is a standard football match?",
    "What is the importance of substitutes in football?",
    "Why are football boots designed the way they are?",
    "How has football evolved over the centuries?",
    "How has women's football grown in popularity?",
    "Why do footballers sign endorsement deals?",
    "How do football clubs generate revenue through merchandising?",
    "What are the dimensions of a professional football goalpost?",
    "Why is the offside rule important in football?",
    "Why do football teams go on pre-season tours?",
    "What role does FIFA play in global football?",
    "Why do many footballers engage in charity work?",
    "How is football watched around the world?",
    "What are some footballers known for?",
    "How does medical staff support football players?",
    "Why do football players wear shin guards?",
    "How do football clubs scout new players?",
    "Which countries have won the World Cup?",
    "Why do football teams change their line-ups?",
    "What financial issues can football clubs face?",
    "What type of ball is used in football?",
    "How are the FIFA rankings determined?",
    "What is the Golden Boot in football?",
    "Why are football players considered role models?",
    "What is the significance of tactics and formations in football?",
    "How far do football fans travel to watch their teams?",
    "What are some famous football rivalries?",
    "What other media has football inspired?",
    "What attracts top-tier talent to the Premier League?",
    "How much do football teams spend on player wages?",
    "What role does VAR play in football?",
    "In what types of weather conditions are football matches played?"
]
